def r
try {
    r = 5
} catch (Exception e) {
    r = 0
} finally {
  r
}