<?xml version="1.0" encoding="UTF-8"?>
<problems>

    <problem>
        <file>ExceptionFromCatchWhichDoesntWrap.java</file>
        <line>41</line>
        <package>com.siyeh.igtest.errorhandling.exception_from_catch</package>
        <problem_class>'throw' inside 'catch' block which ignores the caught exception</problem_class>
        <description>&lt;code&gt;throw&lt;/code&gt; inside 'catch' block ignores the caught exception #loc</description>
    </problem>
</problems>